#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080 


# loads $PLAY_PARAMS
cd $OPENSHIFT_DATA_DIR
source ./playshift-load-config

if [[ ! $? -eq 0 ]]; then
	exit $?
fi

LOG_FILE="${OPENSHIFT_DIY_LOG_DIR}play.log"

export PLAY_PARAMS=`echo $PLAY_PARAMS | sed -s "s/^\(\(\"\(.*\)\"\)\|\('\(.*\)'\)\)\$/\\3\\5/g"`

cd ${OPENSHIFT_REPO_DIR}
chmod +x ${OPENSHIFT_REPO_DIR}target/start
APP_COMMAND="${OPENSHIFT_REPO_DIR}target/start "\
"$PLAY_PARAMS "\
"-Dhttp.port=${OPENSHIFT_DIY_PORT} "\
"-Dhttp.address=${OPENSHIFT_DIY_IP} "\
"-Dconfig.resource=openshift.conf "\
"${JAVA_OPTS}"

echo $APP_COMMAND &>> $LOG_FILE
nohup bash -c "${APP_COMMAND} &>> ${LOG_FILE} 2>&1" &> /dev/null &

